### ISSUE TITLE
Issues with custom colors

### ISSUE THREAD

**Issue by ikitommi** [brcosta/clj-extras-plugin#10]
# thanks for the awesome plugin!

some observations for coloring:

1. namespace color bleeds for fully qualified key with `-` in the name, `::m/missing-key`
2. qualified symbol namespace names could have different color if they are passed as values (instead of used in function position `m/schema`

<img width="314" alt="Screenshot 2022-01-21 at 20 52 45" src="https://user-images.githubusercontent.com/567532/150583882-d2007472-7d81-4caf-bd35-1562de3be919.png">

**Comment by brcosta** [comment]
(1) is fixed on master, we just need to wait for jetbrains to approve it (v 0.5.2). I'll try to add some customization for (2) later! Thanks for reporting :)

**Comment by brcosta** [comment]
Fixed on 0.5.4! :)
