### ISSUE TITLE
Keyword namespace color in discard form

### ISSUE THREAD

**Issue by serioga** [brcosta/clj-extras-plugin#12]
I use color for keyword namespace.
This affects colors in the discard form (colored by Cursive as comment) unexpectedly.

![2022-01-22_100043](https://user-images.githubusercontent.com/527113/150632158-cd284d60-5819-473f-9992-e1cbca992ccb.png)

Clojure Extras (0.5.1)

**Comment by brcosta** [comment]
Fixed on master, we just need to wait for jetbrains to approve it (v 0.5.2)

**Comment by serioga** [comment]
It works, thank you.

**Comment by serioga** [comment]
@brcosta yet another case :-)
```clojure
#_#:foo{:bar 1}
```

**Comment by brcosta** [comment]
Fixed on 0.5.4
