### ISSUE TITLE
Don't ask for "permission" to analyze classpath if .clj-kondo folder exists

### ISSUE THREAD

**Issue by ivarref** [brcosta/clj-extras-plugin#19]
Hi, and thanks for an excellent plugin!

Every time I open a project (quite frequent), I'm always asked if I want to use clj-kondo/Analyze Classpath.

I think it would make sense to automatically analyze Classpath if the `.clj-kondo` folder exists in the project directory.
Would it be possible to make clj-extras do this?

![image](https://user-images.githubusercontent.com/74075/160791757-0a47c377-14ab-4616-a3f4-795a2ceecd71.png)

**Comment by borkdude** [comment]
And maybe additionally: clj-extras-plugin could ask to create a `.clj-kondo` directory in the project root if it didn't exist yet.

**Comment by brcosta** [comment]
Fixed in master, it'll now automatically analyze dependencies if the project already has a .clj-kondo directory, else it will show the notification and create a .clj-kondo directory if the user chooses to run it. Thanks for the tips!

**Comment by ivarref** [comment]
Thanks a lot! :+1:
