### ISSUE TITLE
IntelliJ IDEA 2023.3 compatibility

### ISSUE THREAD

**Issue by ai212983** [brcosta/clj-extras-plugin#51]

**Comment by holyjak** [comment]
Many thanks @brcosta for your continuing maintenance of this awesome  plugin! I see that #52 has been merged, is a release coming up soon? Thank you! <3

**Comment by brcosta** [comment]
It's merged and sent to the marketplace (jetbrains will take a couple days to approve and release), sorry for the delay :)

**Comment by panewman** [comment]
Thanks for the update. Sadly Intellij increased version number just a week ago:
IntelliJ IDEA 2023.3.2 (Community Edition)
Build #IC-233.13135.103, built on December 20, 2023

**Comment by scarytom** [comment]
is there any way we can change this plugin to be more accepting of new IDEA versions?

This is the only plugin that seems to be automatically incompatible with new versions as they are released?
