### ISSUE TITLE
Cannot install 0.7.13 in IntelliJ Ultimate 2024.2

### ISSUE THREAD

**Issue by Sardtok** [brcosta/clj-extras-plugin#59]
Tried updating to the latest version of Clojure Extras by downloading. Checked contents of plugin.xml within the archive and it does say 242.* in the until-build attribute.

Still I get the following error:
![Skjermbilde fra 2024-08-12 15-43-27](https://github.com/user-attachments/assets/7f87a1dc-c50b-411b-a5c7-a4ffbdbe0a88)

Using the following build of IntelliJ:
IntelliJ IDEA 2024.2 (Ultimate Edition)
Build #IU-242.20224.300, built on August 6, 2024

**Comment by zjjfly** [comment]
> Tried updating to the latest version of Clojure Extras by downloading. Checked contents of plugin.xml within the archive and it does say 242.* in the until-build attribute.
> 
> Still I get the following error: ![Skjermbilde fra 2024-08-12 15-43-27](https://private-user-images.githubusercontent.com/613667/357070710-7f87a1dc-c50b-411b-a5c7-a4ffbdbe0a88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjMzODgsIm5iZiI6MTcyMzcyMzA4OCwicGF0aCI6Ii82MTM2NjcvMzU3MDcwNzEwLTdmODdhMWRjLWM1MGItNDExYi1hNWM3LWE0ZmZiZGJlMGE4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxMTU4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZThiMjUyM2RhMmU3OTU2MTgxYzQxZTc2N2ExMDZhMzc4YmNjM2RlNWVhZTRiMzViYTI0MWFjOTc2MTk0YTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mHHXsmN7hl8C1JF09WryB-yyYzmWffiwuwvb0uQRm7A)
> 
> Using the following build of IntelliJ: IntelliJ IDEA 2024.2 (Ultimate Edition) Build #IU-242.20224.300, built on August 6, 2024

#58

**Comment by Sardtok** [comment]
Fixed in #58
