### ISSUE TITLE
Color inconsistency for namespaced keywords

### ISSUE THREAD

**Issue by zharinov** [brcosta/clj-extras-plugin#8]
Pretty strange, but slash in namespaced keywords picks the same color as what is defined for numbers.
Not sure, though, whether this needs to be addressed in this plugin source, or it has something to do with @cursive-ide.

![image](https://user-images.githubusercontent.com/1239644/149941562-0af64ba2-7b7b-4b03-b70b-079b15c30352.png)

**Comment by brcosta** [comment]
It's a clojure-extras problem! I'll try to submit a fix on the next version, tks for reporting :)

**Comment by brcosta** [comment]
Fixed it on master (v0.5.1), Jetbrains should approve it shortly in the marketplace 🎉
