### ISSUE TITLE
Enhancement: add support ANSI escape codes for terminal output

### ISSUE THREAD

**Issue by mikeananev** [brcosta/clj-extras-plugin#9]
**Problem description:** Currently, `clj-extras-plugin` works as dumb terminal when using `println` function and doesn't support ANSI escape codes. These codes are used in many Clojure libraries to make color output.

**Steps to reproduce:**
1. Create new empty project and add [hashp library](https://github.com/weavejester/hashp) as dependency. This library uses ANSI terminal codes during output to console.
2. Make color output to REPL console using ANSI escape codes `#p (println "hello world!")`

**Current behaviour:**
<img width="811" alt="Снимок экрана 2022-01-20 в 08 26 26" src="https://user-images.githubusercontent.com/45389186/150278948-6c53e15d-148f-4ee4-9d12-c566516fb6bd.png">

**Expected behaviour**:

<img width="516" alt="Снимок экрана 2022-01-20 в 08 25 07" src="https://user-images.githubusercontent.com/45389186/150278813-5c388932-3c29-4236-8246-a8953d2c94cd.png">

**Comment by brcosta** [comment]
Should be fixed it on master (v0.5.1), we just need to wait for Jetbrains to approve it on the marketplace :)

**Comment by mikeananev** [comment]
Got update. Fixed! 
Thank you.
